name: Build

on:
  - push

env:
  imageName: ${{ secrets.DOCKER_REGISTRY }}/nginx

jobs:
  build:
    name: 'Build and publish image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: |
          docker build -t $imageName .

      - name: Build test image
        run: |
          echo "FROM " $imageName >> test/Dockerfile
          echo "ADD . /home/app" >> test/Dockerfile

          docker build -t test test/

      - name: Test if image is built correctly
        run: |
          docker run --rm -d --name test -p8080:80 test
          sleep 3

          echo "Test if index.html works"
          test=`curl -sS localhost:8080`
          [ "$test" == "it works!" ] || exit 1;

          echo "Test if index.txt works"
          test=`curl -sS localhost:8080/index.txt`
          [ "$test" == "txt works!" ] || exit 1;

          echo "Test if configuration files are not exposed"
          test=`curl -sS localhost:8080/.nginx/test.conf`
          [ "$test" == "it works!" ] || exit 1;

          echo "Build completed"

      - name: Push image
        run: |
          docker push $imageName

      - name: Clean up
        if: ${{ always() }}
        run: |
          docker stop test || true
          docker rmi test
          docker image prune -f
